CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_at" timestamp DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_users_email ON users(email);


CREATE TABLE "user_settings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer UNIQUE NOT NULL,
  "currency" varchar(10) DEFAULT 'EUR',
  "language" varchar(10) DEFAULT 'en',
  "theme" varchar(20) DEFAULT 'light',

  FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);


CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "name" varchar(100) NOT NULL,
  "type" varchar(20) NOT NULL,
  "color" varchar(20),
  "created_at" timestamp DEFAULT NOW(),

  FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE,

  CONSTRAINT chk_category_type CHECK (type IN ('expense', 'income'))
);

CREATE INDEX idx_categories_user_id ON categories(user_id);


CREATE TABLE "transactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "category_id" integer,
  "amount" decimal(10,2) NOT NULL,
  "description" text,
  "date" date NOT NULL,
  "created_at" timestamp DEFAULT NOW(),

  FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE,
  FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL
);

CREATE INDEX idx_transactions_user_id ON transactions(user_id);
CREATE INDEX idx_transactions_category_id ON transactions(category_id);
CREATE INDEX idx_transactions_date ON transactions(date);


CREATE TABLE "budgets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "category_id" integer,
  "limit_amount" decimal(10,2) NOT NULL,
  "period" varchar(20) DEFAULT 'monthly',
  "start_date" DATE NOT NULL,
  "end_date" DATE NOT NULL,
  "created_at" timestamp DEFAULT NOW(),

  FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE,
  FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL
);

CREATE INDEX idx_budgets_user_id ON budgets(user_id);


CREATE TABLE "tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT NOW()
);


CREATE TABLE "expense_tags" (
  "expense_id" integer NOT NULL,
  "tag_id" integer NOT NULL,

  PRIMARY KEY ("expense_id", "tag_id"),

  FOREIGN KEY ("expense_id") REFERENCES "transactions"("id") ON DELETE CASCADE,
  FOREIGN KEY ("tag_id") REFERENCES "tags"("id") ON DELETE CASCADE
);